#  Copyright (c) 2006-2017, Puzzle ITC GmbH. This file is part of
#  PuzzleTime and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/puzzletime.


# ############################## #
# Global settings for puzzleTime #
# ############################## #

# Array of holidays with a fixed date. [day, month]
regular_holidays:
  -
    - 1
    - 1
  -
    - 2
    - 1
  -
    - 1
    - 8
  -
    - 25
    - 12
  -
    - 26
    - 12

api_client:
  user: <%= ENV['RAILS_API_USER'] || SecureRandom.hex %>
  password: <%= ENV['RAILS_API_PASSWORD'] || SecureRandom.hex %>

# LDAP configuration
ldap:
  connection:
    host: <%= ENV['RAILS_LDAP_HOST'] %>
    port: <%= ENV['RAILS_LDAP_PORT'] || 636 %>
    <% if ENV['RAILS_LDAP_ENCRYPTION'] %>
    encryption:
      method: <%= ENV['RAILS_LDAP_ENCRYPTION'] %>
    <% end %>
  auth:
    binduser: <%= ENV['RAILS_LDAP_BINDUSER'] %>
    bindpassword: <%= ENV['RAILS_LDAP_BINDPASSWORD'] %>
    root_cert: <%= ENV['RAILS_LDAP_ROOT_CERT'] %>
    chain_cert: <%= ENV['RAILS_LDAP_CHAIN_CERT'] %>
  user_dn: <%= ENV['RAILS_LDAP_USER_DN'] %>
  external_dn: <%= ENV['RAILS_LDAP_EXTERNAL_DN'] %>
  group: <%= ENV['RAILS_LDAP_GROUP_DN'] %>

# OmniAuth configuration
auth:
  keycloakopenid:
    host: <%= ENV['AUTH_KEYCLOAK_HOST'] %>
    realm: <%= ENV['AUTH_KEYCLOAK_REALM'] %>
    client: <%= ENV['AUTH_KEYCLOAK_CLIENT'] %>
    secret: <%= ENV['AUTH_KEYCLOAK_SECRET'] %>
    fields:
      ldapname: ['extra', 'raw_info', 'preferred_username']
      email: ['info', 'email']
  saml:
    cert_fingerprint: <%= ENV['AUTH_SAML_CERT_FINGERPRINT'] %>
    sso_target_url: <%= ENV['AUTH_SAML_SSO_TARGET_URL'] %>

# Highrise configuration
highrise:
  url: <%= ENV['RAILS_HIGHRISE_URL'] || 'https://highrisehq.com' %>
  api_token: <%= ENV['RAILS_HIGHRISE_TOKEN'] %>

small_invoice:
  url: https://api.smallinvoice.com
  api_token: <%= ENV['RAILS_SMALL_INVOICE_TOKEN'] %>
  request_rate: <%= ENV['RAILS_SMALL_INVOICE_REQUEST_RATE'] || 1 %>
  constants:
    account_id: 0 # none
    esr: true
    esr_singlepage: false
    lsvplus: false
    debit_direct: false
    language: de
    paypal: false
    paypal_url:
    vat_included: false
    client_type: 1 # company
    position_type_id: 1 # service
    unit_id: 1 # hours
    gender_id: 2 # female


# Default values
defaults:
  report_type: absolute_day
  start_hour: 8
  country: <%= ENV['RAILS_PTIME_COUNTRY'] || 'CH' %>
  vat: <%= ENV['RAILS_PTIME_VAT'] || 7.7 %>
  currency: <%= ENV['RAILS_PTIME_CURRENCY'] || 'CHF' %>
  # Month number the business year starts (e.g. 1 for 1.1.YYYY, 7 for 1.7.YYYY)
  business_year_start_month: 7
  payment_period: 30 # days
  payment_periods:
    - 30
    - 45
    - 60

work_items:
  path_separator: '-'

employees:
  # The initial vacation days are used to transfer the current vacation balance of each employee
  # when introducing puzzle time. At some point, it will no be required to edit that value anymore.
  initial_vacation_days_editable: <%= ENV['RAILS_PTIME_INITIAL_VACATION_DAYS_EDITABLE'].try(:downcase) == 'true' %>

clients:
  # The client id of the company using this application
  company_id: <%= ENV['RAILS_PTIME_COMPANY_ID'] || 4 %>

committed_worktimes:
  notification:
    days_at_end_of_month: 7
    days_at_beginning_of_month: 3

help:
  url: https://twiki.puzzle.ch/bin/view/PITC_PuzzleTime/Besonderheiten

meal_compensation:
  active: <%= ENV['RAILS_PTIME_MEALTIME_COMPENSATION_ACTIVE'].try(:downcase) == 'true' %>
  url: <%= ENV['RAILS_PTIME_MEALTIME_COMPENSATION_URL'] %>

reports:
  # The minimum values for a given color in order reports.
  orders:
    billability:
      green: 90
      orange: 80
      red: 0
    average_rate:
      green: 150
      yellow: 130
      orange: 100
      red: 0
  workload:
    billability:
      green: 95
      orange: 90
      red: 0
    load:
      green: 90
      orange: 80
      red: 0
    worktime_balance:
      lower_limit: 0

mailer:
  employee:
    worktime_deleted:
      from: <%= ENV['RAILS_PTIME_MAILER_EMPLOYEE_WORKTIME_DELETED_FROM'] || 'time@puzzle.ch' %>
