name: 'Lint, test and image build on push'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  lint:
    uses: ./.github/workflows/reusable-lint.yaml

  test:
    uses: ./.github/workflows/reusable-test.yaml

  build-int:
    needs: [lint, test]
    uses: ./.github/workflows/reusable-build.yaml
    with:
      environment: pitc-ptime-int
      project_name: pitc-ptime-int
      push: true
      registry: registry.puzzle.ch
    secrets:
      PUZZLE_REGISTRY_USERNAME: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
      PUZZLE_REGISTRY_TOKEN: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

  sbom-int:
    needs: build-int
    uses: ./.github/workflows/reusable-sbom.yaml
    with:
      project_name: pitc-ptime-int
      artifact-prefix: int-
    secrets:
      dependency_track_url: ${{ secrets.DEPTRACK_URL }}
      dependency_track_api_key: ${{ secrets.DEPTRACK_API_KEY }}

  build-prod:
    needs: [lint, test]
    uses: ./.github/workflows/reusable-build.yaml
    with:
      environment: pitc-ptime-prod
      project_name: pitc-ptime-prod
      push: true
      registry: registry.puzzle.ch
    secrets:
      PUZZLE_REGISTRY_USERNAME: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
      PUZZLE_REGISTRY_TOKEN: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

  sbom-prod:
    needs: build-prod
    uses: ./.github/workflows/reusable-sbom.yaml
    with:
      project_name: pitc-ptime-prod
      artifact-prefix: prod-
    secrets:
      dependency_track_url: ${{ secrets.DEPTRACK_URL }}
      dependency_track_api_key: ${{ secrets.DEPTRACK_API_KEY }}

  build-pude:
    needs: [lint, test]
    uses: ./.github/workflows/reusable-build.yaml
    with:
      environment: pude-ptime-prod
      project_name: pude-ptime-prod
      push: true
      registry: registry.puzzle.ch
    secrets:
      PUZZLE_REGISTRY_USERNAME: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
      PUZZLE_REGISTRY_TOKEN: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

  sbom-pude:
    needs: build-pude
    uses: ./.github/workflows/reusable-sbom.yaml
    with:
      project_name: pude-ptime-prod
      artifact-prefix: pude-
    secrets:
      dependency_track_url: ${{ secrets.DEPTRACK_URL }}
      dependency_track_api_key: ${{ secrets.DEPTRACK_API_KEY }}
