name: "Code Style Review"

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "doc/**"
      - "**.md"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "Rubocop"
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-minitest:gemfile rubocop-performance:gemfile rubocop-rails:gemfile
          reporter: github-pr-review
          level: error

      - name: "Install HAML-Lint"
        run: "gem install haml-lint"
      - name: "Set up reviewdog"
        uses: reviewdog/action-setup@v1
      - name: "Run reviewdog HAML-Lint"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          haml-lint |
          reviewdog \
          -efm="%f:%l %m" \
          -name="Haml-lint" \
          -reporter=github-pr-review \
          -level=error \
          -diff="git diff $DIFF_BRANCH"
