name: 'Rails Unit Tests'

on:
  workflow_call:

jobs:
  minitest:
    runs-on: 'ubuntu-latest'

    services:
      postgres:
        image: 'postgres:11'
        env:
          POSTGRES_PASSWORD: 'postgres'
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: 'memcached'
        ports: [ '11211:11211' ]

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: 'Build and test with Rake'
      env:
        RAILS_TEST_DB_NAME: 'postgres'
        RAILS_TEST_DB_USERNAME: 'postgres'
        RAILS_TEST_DB_PASSWORD: 'postgres'
        RAILS_ENV: 'test'
        CI: 'true'
        PGDATESTYLE: German
      run: |
        sudo apt-get -yqq install libpq-dev libvips-dev
        gem install bundler --version '~> 2'
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails assets:precompile
        bundle exec rails test
